### ISSUE TITLE
Add Loading Animation to Comment Button

### ISSUE THREAD

**Issue by daniel-koti** [wllysses/tweet-app#1]
### Problem Description

Currently, when posting a comment in the project, there is no visual indication that the request is being processed. This can lead to confusion for users, especially on slower connections.

### Proposed Improvement

I would like to suggest adding a loading animation to the comment button to visually indicate that the request is in progress. This would provide a better user experience, clearly conveying that the action is being processed.

Nice work 🔥

**Comment by wllysses** [comment]
Firstly, thank you for your collaboration. Really it is something that can be implemented in the project. I will do this as soon as possible.

**Comment by wllysses** [comment]
Suggestion implemented. Thanks!
