### ISSUE TITLE
Add Deletion Confirmation to the Delete Comment Button

### ISSUE THREAD

**Issue by daniel-koti** [wllysses/tweet-app#2]
### Problem Description

Currently, when clicking on the delete comment button, the action is executed immediately without any confirmation. This can lead to accidental deletions since the action is irreversible.

### Proposed Improvement

I would like to suggest adding a deletion confirmation to the delete comment button. This can be achieved through a confirmation pop-up or a context menu, prompting the user to confirm the deletion before the action is carried out.

**Comment by wllysses** [comment]
Really it is something that can be implemented in the project. I will do this as soon as possible.

**Comment by wllysses** [comment]
Suggestion implemented. Thanks!

**Comment by wllysses** [comment]
Suggestion implemented. Thanks!
