### ISSUE TITLE
Add env-example to the project

### ISSUE THREAD

**Issue by lazarok09** [wllysses/tweet-app#3]
## Problem Description:

I would like there to be a way to input Prisma environment data.

### Reproduction Steps:

Clone the project.
Run yarn to install dependencies.
Observe the log error.
#### Expected Behavior:

After cloning the project, navigate to the env-example file to view the necessary credential variables for the application to function.

### Screenshots:
![image](https://github.com/wllysses/tweet-app/assets/45147892/2a006469-52fa-4d63-b12b-4fb10385aeba)

### Environment:

Operating System: Ubuntu WSL2
Browser/Version: Edge, Chrome

**Comment by wllysses** [comment]
Thanks for the collaboration. I just added a .env.example file containing the necessary environment variables, just filling them with the values ​​obtained in your environment.
